#define T_TYPEDEF  1
#define T_CHAR     2  
#define T_INT     3
#define T_FLOAT  4
#define T_STRING  5
#define T_CONST  6
#define T_UNION  7
#define T_CLASS  8
#define T_PRIVATE 9
#define T_PROTECTED 10
#define T_PUBLIC  11
#define T_STATIC 12
#define T_VOID 13
#define T_LIST 14
#define T_CONTINUE 15
#define T_BREAK 16
#define T_THIS 17
#define T_IF 18
#define T_ELSE 19
#define T_WHILE 20
#define T_FOR 21
#define T_RETURN  22 
#define T_LENGTH 23
#define T_NEW 24
#define T_CIN 25
#define T_COUT 26
#define T_MAIN 27

#define T_ID 28
#define T_ICONST 29
#define T_FCONST 30
#define T_CCONST 31
#define T_SCONST 32

#define T_OROP 33
#define T_ANDOP 34 
#define T_EQUOP 35 
#define T_RELOP 36 
#define T_ADDOP 37 
#define T_MULOP 38 
#define T_NOTOP 39 
#define T_INCDEC 40

#define T_LPAREN 41
#define T_RPAREN 42
#define T_SEMI 43
#define T_DOT 44
#define T_COMMA 45
#define T_ASSIGN 46
#define T_COLON 47
#define T_LBRACK 48
#define T_RBRACK 49
#define T_REFER 50
#define T_LBRACE 51
#define T_RBRACE 52
#define T_METH 53
#define T_INP 54
#define T_OUT 55
#define T_LISTFUNC 55

#define T_EOF 0